alessandria/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from alessandria import views
from alessandria import ajax

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    url(r'reader_borrow/add/$', views.ReaderBorrowCreateView.as_view(), name='reader_borrow_add'),
    url(r'reader_borrow/(?P<pk>\d+)/$', views.ReaderBorrowUpdateView.as_view(), name='reader_borrow_update'),
    url(r'reader_borrow/list/$', views.ReaderBorrowListView.as_view(), name='reader_borrow_list'),
    url(r'reader_borrow/list/(?P<display>\w+)/$', views.ReaderBorrowListView.as_view(), name='reader_borrow_list'),
    url(r'reader_borrow/(?P<pk>\d+)/delete/$', views.ReaderBorrowDeleteView.as_view(), name='reader_borrow_delete'),

    url(r'reader/add/$', views.ReaderCreateView.as_view(), name='reader_add'),
    url(r'reader/(?P<pk>\d+)/$', views.ReaderUpdateView.as_view(), name='reader_update'),
    url(r'reader/list/$', views.ReaderListView.as_view(), name='reader_list'),
    url(r'reader/(?P<pk>\d+)/delete/$', views.ReaderDeleteView.as_view(), name='reader_delete'),
    url(r'reader/(?P<pk>\d+)/disable/$', views.ReaderDisableView.as_view(), name='reader_disable'),
    url(r'reader/(?P<pk>\d+)/enable/$', views.ReaderEnableView.as_view(), name='reader_enable'),

    url(r'author/add/(?P<redirect_to_book>\w+)?$', views.AuthorCreateView.as_view(), name='author_add'),
    url(r'author/(?P<pk>\d+)/$', views.AuthorUpdateView.as_view(), name='author_update'),
    url(r'author/(?P<pk>\d+)/delete/$', views.AuthorDeleteView.as_view(), name='author_delete'),
    url(r'author/list/$', views.AuthorListView.as_view(), name='author_list'),

    url(r'publisher/add/(?P<redirect_to_book>\w+)?$', views.PublisherCreateView.as_view(), name='publisher_add'),
    url(r'publisher/(?P<pk>\d+)/$', views.PublisherUpdateView.as_view(), name='publisher_update'),
    url(r'publisher/(?P<pk>\d+)/delete/$', views.PublisherDeleteView.as_view(), name='publisher_delete'),
    url(r'publisher/list/$', views.PublisherListView.as_view(), name='publisher_list'),
    url(r'publisher/(?P<publisher_id>\d+)/books/$', views.book_list_by_publisher, name='book_list_by_publisher'),

    url(r'book/add/(?P<from_external_page>\w+)?$', views.BookCreateView.as_view(), name='book_add'),
    url(r'book/(?P<pk>\d+)/$', views.BookUpdateView.as_view(), name='book_update'),
    url(r'book/(?P<pk>\d+)/delete/$', views.BookDeleteView.as_view(), name='book_delete'),
    url(r'book/list/$', views.BookListView.as_view(), name='book_list'),
    url(r'book/save_book_form_to_session/(?P<dest_url>\S+)/$', views.save_book_form_to_session, name='save_book_form_to_session'),

    url(r'book/isbn/import/$', views.BookIsbnImportView.as_view(), name='book_isbn_import'),

    url(r'bookcopy/add/(?P<book_id>\d+)/$', views.BookCopyCreateView.as_view(), name='bookcopy_add'),
    url(r'bookcopy/(?P<pk>\d+)/$', views.BookCopyUpdateView.as_view(), name='bookcopy_update'),
    url(r'bookcopy/(?P<pk>\d+)/disable/$', views.BookCopyDisableView.as_view(), name='bookcopy_disable'),
    url(r'bookcopy/(?P<pk>\d+)/delete/$', views.BookCopyDeleteView.as_view(), name='bookcopy_delete'),

    url(r'ajax/get/book_sub_categories/?$', ajax.get_book_sub_categories, name='get_book_sub_categories'),
]

alessandria/forms.py
import datetime

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.db.utils import OperationalError
from ajax_select.fields import AutoCompleteSelectField, AutoCompleteSelectMultipleField
from django_countries import countries

from alessandria.models import (
    GeneralConfiguration, ReaderBorrow, Reader, Author, Publisher, Book, BookAudience, BookCopy
)


max_borrow_days = 0
default_country = None
try:
    if GeneralConfiguration.objects.first() is not None:
        max_borrow_days = GeneralConfiguration.objects.first().max_borrow_days
except OperationalError:
    # To prevent "django.db.utils.OperationalError" when reseting the DB
    pass

_l_countries = sorted(dict(countries).items())
_l_default_exclude_fields = ['created_by', 'created_on', 'modified_by', 'modified_on']
_css_class_required_field = 'required'


class CommonForm(forms.ModelForm):
    required_css_class = 'required'  # Used in the template


class ReaderBorrowForm(CommonForm):
    class Meta:
        model = ReaderBorrow
        exclude = _l_default_exclude_fields
    borrowed_date = forms.DateField(
        label=Meta.model._meta.get_field('borrowed_date').verbose_name,
        initial=datetime.date.today()
    )
    borrow_due_date = forms.DateField(
        label=Meta.model._meta.get_field('borrow_due_date').verbose_name,
        initial=datetime.date.today() + datetime.timedelta(days=max_borrow_days)
    )

    # 'bookcopy_list' and 'reader_list' are registered lookups.py
    bookcopy = AutoCompleteSelectField(
        'bookcopy_list', label=Meta.model._meta.get_field('bookcopy').verbose_name,
        required=False, help_text=None, plugin_options={'autoFocus': True, 'minLength': 3}
    )
    reader = AutoCompleteSelectField(
        'reader_list', label=Meta.model._meta.get_field('reader').verbose_name,
        required=False, help_text=None, plugin_options={'autoFocus': True, 'minLength': 3}
    )

    def clean_reader(self):
        if self.cleaned_data['reader'] is None:
            raise forms.ValidationError(_("Please select a reader"))
        return self.cleaned_data['reader']

    def clean_bookcopy(self):
        bookcopy = self.cleaned_data['bookcopy']
        if bookcopy is None:
            raise forms.ValidationError(_("Please select a a book copy"))
        # Make sure this bookcopy was not already borrowed by somebody else
        already_borrowed = ReaderBorrow.objects.filter(bookcopy=bookcopy).filter(returned_on=None).first()
        error = False
        if already_borrowed is not None:
            if self.instance is not None:  # Update mode
                if already_borrowed.id != self.instance.id:  # Not updating the current record
                    error = True
            else:  # Create mode
                error = True
            if error:
                raise forms.ValidationError(
                    _('This book copy was already borrowed by {0}.').format(already_borrowed.reader)
                )
        return bookcopy


class ReaderForm(CommonForm):
    class Meta:
        model = Reader
        exclude = _l_default_exclude_fields + ['number', 'disabled_on']

    def clean(self):
        cleaned_data = super().clean()

        homonyms = Reader.objects.filter(
            first_name__iexact=cleaned_data.get("first_name")
        ).filter(
            last_name__iexact=cleaned_data.get("last_name")
        ).filter(
            birthday=cleaned_data.get("birthday")
        ).filter(
            city__iexact=cleaned_data.get("city")
        ).exclude(
            id=self.instance.id
        )
        if homonyms.exists():
            self.add_error('last_name', _("This reader already exists."))


class ReaderSearchForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Override the fields making it NOT mandatory
        self.fields['last_name'].required = False

    reader_enabled = forms.BooleanField(label=_("Readers enabled"), initial=True, required=False)

    class Meta:
        model = Reader
        fields = ('last_name',)


class ReaderEnableDisableForm(CommonForm):
    class Meta:
        model = Reader
        fields = ()


class AuthorForm(CommonForm):
    class Meta:
        model = Author
        exclude = _l_default_exclude_fields + ['is_isbn_import', 'import_source']

    def clean(self):
        cleaned_data = super().clean()

        homonyms = Author.objects.filter(
            first_name__iexact=cleaned_data.get("first_name")
        ).filter(
            last_name__iexact=cleaned_data.get("last_name")
        ).filter(
            birthday=cleaned_data.get("birthday")
        ).exclude(
            id=self.instance.id
        )
        if homonyms.exists():
            self.add_error('last_name', _("This author already exists."))


class AuthorSearchForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('last_name',)


class PublisherForm(CommonForm):
    class Meta:
        model = Publisher
        exclude = _l_default_exclude_fields + ['is_isbn_import', 'import_source']

    def clean(self):
        cleaned_data = super().clean()

        if Publisher.objects.filter(name__iexact=cleaned_data.get("name")).exclude(id=self.instance.id).exists():
            self.add_error('name', _("This publisher already exists."))


class PublisherSearchForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ('name',)


class BookForm(CommonForm):

    class Meta:
        model = Book
        exclude = _l_default_exclude_fields + ['related_to', 'cover_pic']

    title = forms.CharField(
        label=Meta.model._meta.get_field('title').verbose_name,
        widget=forms.TextInput(attrs={'size': '40'})
    )

    # 'author_list' and 'publisher_list' are registered lookups.py
    authors = AutoCompleteSelectMultipleField(
        'author_list', label=Meta.model._meta.get_field('authors').verbose_name,
        required=False, help_text=None, plugin_options={'autoFocus': True, 'minLength': 3}
    )
    publishers = AutoCompleteSelectMultipleField(
        'publisher_list', label=Meta.model._meta.get_field('publishers').verbose_name,
        required=False, help_text=None, plugin_options={'autoFocus': True, 'minLength': 3}
    )
    audiences = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(), label=Meta.model._meta.get_field('audiences').verbose_name,
        queryset=BookAudience.objects.all()
    )

    def clean_authors(self):
        if not any(self.cleaned_data['authors']):  # It is a list
            raise forms.ValidationError(_("Please select at least one author"))
        return self.cleaned_data['authors']

    def clean_publishers(self):
        if not any(self.cleaned_data['publishers']):  # It is a list
            raise forms.ValidationError(_("Please select at least one publisher"))
        return self.cleaned_data['publishers']


class BookSearchForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Override the fields making it NOT mandatory
        self.fields['isbn_nb'].required = False
        self.fields['title'].required = False
        self.fields['category'].required = False

    author_name = forms.CharField(label=_('Author'), required=False)
    has_copy = forms.BooleanField(label=_('Has copy'), initial=True)
    took_away = forms.BooleanField(label=_('Took away'), initial=False, required=False)

    class Meta:
        model = Book
        fields = ('isbn_nb', 'title', 'category', 'sub_category',)


class BookCopyForm(CommonForm):
    class Meta:
        model = BookCopy
        exclude = _l_default_exclude_fields + ['number', 'book', 'disabled_on']

    registered_on = forms.DateField(
        label=Meta.model._meta.get_field('registered_on').verbose_name, initial=datetime.date.today
    )


class BookCopyDisableForm(CommonForm):
    class Meta:
        model = BookCopy
        fields = ('disabled_on',)

    disabled_on = forms.DateField(
        label=Meta.model._meta.get_field('disabled_on').verbose_name,
        required=True
    )

alessandria/templates/alessandria/_inc_form_edit_buttons_std.html
{% load i18n %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
        {% if form.instance.id > 0 and delete_url %}
            <a class="btn btn-danger" href="{% url delete_url form.instance.id %}">{% trans "Delete" %}</a>
        {% endif %}
    </div>
</div>

alessandria/templates/alessandria/_inc_form_edit_content_std.html
{% load tag_extras %}

{% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label {{ field.css_classes }}">{{ field.label }}</label>
        <div class="col-sm-10">
            {{ field|addcss:"form-control" }}
            {% if field.errors %}
                <div class="text-danger">{{ field.errors }}</div>
            {% endif %}
        </div>
    </div>
{% endfor %}

alessandria/templates/alessandria/author_list.html
{% extends 'alessandria/base_tpl.html' %}
{% load i18n %}

{% block title %}{% trans "Author list" %}{% endblock %}

{% block pageTitle %}{% trans "Author list" %}{% endblock %}

{% block content %}

<form class="form-horizontal" action="{% url 'alessandria:author_list' %}" method="post" role="form">{% csrf_token %}
    {% include 'alessandria/_inc_form_search_std.html' %}
</form>

<div class="row">
    <div class="col-md-12">
        {% include 'alessandria/_inc_paginator_list.html' %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th><a href="{% url 'alessandria:author_list' %}?order_field=last_name">{% trans "Name" %}</a></th>
                    <th>Date de naissance</th>
                    <th><a href="{% url 'alessandria:author_list' %}?order_field=created_on">{% trans "Created on" %}</a></th>
                </tr>
            </thead>
            <tbody>
                {% for author in object_list %}
                <tr>
                    <td><a href="{% url 'alessandria:author_update' author.id %}">{{ author }}</a></td>
                    <td>{{ author.birthday|default:"" }}</td>
                    <td>{{ author.created_on }}</td>
                </tr>
                {% empty %}
                    <tr><td colspan="3">{% trans "No author." %}</td></tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

alessandria/templates/alessandria/base_tpl.html
{% load i18n %}
{% load staticfiles %}
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Alessandria">
        <meta name="author" content="Marc SCHNEIDER">
        <!--link rel="icon" href="../../favicon.ico" -->
      
        <title>{% block title %}Alessandria - {{ LIBRARY_NAME }}{% endblock %}</title>
      
        <link rel="stylesheet" href="{% static 'alessandria/layout/bootstrap/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'alessandria/layout/style.css' %}" />
        <link rel="stylesheet" href="{% static 'alessandria/layout/font-awesome/css/font-awesome.min.css' %}">
        {% block head %}{% endblock %}
    </head>

    <body>
        <div class="container">
            <!-- Static navbar -->
            <div class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">{% trans "Toggle navigation" %}</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'alessandria:home' %}">{% trans "Home" %}</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Borrowings" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'alessandria:reader_borrow_add' %}">{% trans "Add" %}</a></li>
                                    <li><a href="{% url 'alessandria:reader_borrow_list' 'current' %}">{% trans "Current borrowings" %}</a></li>
                                    <li><a href="{% url 'alessandria:reader_borrow_list' 'late' %}">{% trans "Late borrowings" %}</a></li>
                                    <li><a href="{% url 'alessandria:reader_borrow_list' %}">{% trans "All borrowings" %}</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Books" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'alessandria:book_add' %}">{% trans "Add" %}</a></li>
                                    <li><a href="{% url 'alessandria:book_isbn_import' %}">{% trans "ISBN import" %}</a></li>
                                    <li><a href="{% url 'alessandria:book_list' %}">{% trans "List" %}</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Readers" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'alessandria:reader_add' %}">{% trans "Add" %}</a></li>
                                    <li><a href="{% url 'alessandria:reader_list' %}">{% trans "List" %}</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Authors" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'alessandria:author_add' %}">{% trans "Add" %}</a></li>
                                    <li><a href="{% url 'alessandria:author_list' %}">{% trans "List" %}</a></li>
                                    <!--li class="divider"></li>
                                    <li class="dropdown-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li-->
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Publishers" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'alessandria:publisher_add' %}">{% trans "Add" %}</a></li>
                                    <li><a href="{% url 'alessandria:publisher_list' %}">{% trans "List" %}</a></li>
                                </ul>
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                            {% if user.is_authenticated %}
                                <a href="{% url 'alessandria:logout' %}">{% trans "Log out" %} {{ user.first_name }}</a>
                            {% else %}
                                <a href="{% url 'alessandria:login' %}">{% trans "Log in" %}</a>
                            {% endif %}
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/admin">{% trans "Administration" %}</a></li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "History" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    {% for item in request.session.user_nav_list %}
                                        <li><a href="{{ item.0 }}">{{ item.1 }}</a></li>
                                     {% empty %}
                                        <li>{% trans "Empty" %}</li>
                                    {% endfor %}
                                </ul>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
            </div>
          
            <div class="container">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% block pageTitle %}Alessandria{% endblock %}</h3>
                    </div>
                    <div class="panel-body">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div><!-- /.container -->
        <div align="center">
            Alessandria - Licence GNU GPLv3 - {{ VERSION|safe }} - {{ LIBRARY_NAME }}
        </div>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'alessandria/layout/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'alessandria/layout/bootstrap/js/bootstrap.min.js' %}"></script>
        {% block jscript %}{% endblock %}
    </body>
</html>

alessandria/templates/alessandria/book_list.html
{% extends 'alessandria/base_tpl.html' %}
{% load i18n %}

{% block title %}{% trans "Book list" %}{% endblock %}

{% block pageTitle %}{% trans "Book list" %}{% endblock %}

{% block content %}

<form class="form-horizontal" action="{% url 'alessandria:book_list' %}" method="post" role="form">{% csrf_token %}
    {% include 'alessandria/_inc_form_search_std.html' %}
</form>

<div class="row">
    <div class="col-md-12">
        {% include 'alessandria/_inc_paginator_list.html' %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th><a href="{% url 'alessandria:book_list' %}?order_field=title">{% trans "Title" %}</a></th>
                    <th>Auteur</th>
                    <th><a href="{% url 'alessandria:book_list' %}?order_field=isbn_nb">{% trans "ISBN number" %}</a></th>
                    <th># Exemplaires</th>
                    <th><a href="{% url 'alessandria:book_list' %}?order_field=created_on">{% trans "Created on" %}</a></th>
                </tr>
            </thead>
            <tbody>
                {% for book in object_list %}
                <tr>
                    <td><a href="{% url 'alessandria:book_update' book.id %}">{{ book.title }}</a></td>
                    <td><a href="{% url 'alessandria:author_update' book.authors.first.id %}">{{ book.authors.first }}</td>
                    <td>{{ book.isbn_nb|default:"-" }}</td>
                    <td>{{ book.get_nb_copy }}</td>
                    <td>{{ book.created_on }}</td>
                </tr>
                {% empty %}
                    <tr><td colspan="5">{% trans "No book." %}</td></tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

alessandria/templates/alessandria/bookcopy_detail.html
{% extends 'alessandria/base_tpl.html' %}
{% load i18n %}
{% load tag_extras %}

{% block title %}{% trans "Book sample" %}{% endblock %}

{% block head %}
    <link rel="stylesheet" href="/static/alessandria/layout/bootstrap_datepicker/css/bootstrap-datepicker3.css">
{% endblock %}

{% block pageTitle %}{% trans "Book sample" %}:&nbsp;{{ form.instance.number|default:_("new") }} ({{ form.instance.book }}){% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        {% include 'alessandria/_inc_form_edit_header.html' %}
        {% if form.instance.is_disabled %}
            <div class="textInfo">{% trans "This sample was removed." %}</div>
        {% endif %}
        <div class="panel panel-info">
            <div class="panel-body">
                <form class="form-horizontal" action="" method="post" role="form">{% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label {{ field.css_classes }}">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field|addcss:"form-control" }}
                            {% if field.errors %}
                                <div class="text-danger">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                    {% if form.instance.is_disabled %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ form.instance.disabled_on_label }}</label>
                        <div class="col-sm-10">
                             {{ form.instance.disabled_on }}
                        </div>
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
                            {% if form.instance.id > 0 %}
                                {% if not form.instance.is_disabled %}
                                    <a class="btn btn-warning" href="{% url 'alessandria:bookcopy_disable' form.instance.id %}">{% trans "Take out" %}</a>
                                {% endif %}
                                {% if not form.instance.was_borrowed %}
                                    <a class="btn btn-danger" href="{% url 'alessandria:bookcopy_delete' form.instance.id %}">{% trans "Delete" %}</a>
                                {% endif %}
                            {% endif %}
                            <a class="btn" href="{% url 'alessandria:book_update' form.instance.book.id %}">{% trans "Cancel" %}</a>
                        </div>
                    </div>
                </form>
                {% include 'alessandria/_inc_form_edit_footer.html' %}
            </div>
        </div>
    </div><!-- /.col-sm- -->
</div>
{% endblock %}

{% block jscript %}
<script type="text/javascript" src="/static/alessandria/layout/jquery-ui/jquery-ui.min.js"></script>
<script src="/static/alessandria/layout/bootstrap_datepicker/js/bootstrap-datepicker.min.js"></script>
<script src="/static/alessandria/layout/bootstrap_datepicker/locales/bootstrap-datepicker.fr.min.js"></script>
<script>
{% get_current_language as LANGUAGE_CODE %}
$(function() {
    $('#id_registered_on').datepicker({
      language: "{{ LANGUAGE_CODE }}",
      autoclose: true,
      todayHighlight: true,
    });
    $('#id_price_date').datepicker({
      language: "{{ LANGUAGE_CODE }}",
      autoclose: true,
      todayHighlight: true,
    });
});
</script>
{% endblock %}

alessandria/templates/alessandria/confirm_delete.html
{% extends 'alessandria/base_tpl.html' %}
{% load i18n %}

{% block title %}{% trans "Confirm suppression" %}{% endblock %}

{% block pageTitle %}{% trans "Confirm suppression" %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm-12">
        <form action="" method="post">{% csrf_token %}
            <p>{% trans "Do you really want to delete" %} "{{ object }}" ?</p>
            <button type="submit" class="btn btn-danger">{% trans "Confirm" %}</button>
        </form>
    </div><!-- /.col-sm-12 -->
</div>
{% endblock %}

alessandria/templates/alessandria/index.html
{% extends 'alessandria/base_tpl.html' %}
{% load i18n %}

{% block title %}{{ LIBRARY_NAME }}{% endblock %}

{% block pageTitle %}{% trans "Hello" %}, {{ user.first_name }}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "News" %}</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th width="15%">{% trans "Date" %}</th>
                            <th width="85%">{% trans "News" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for appli_news in last_appli_news_list %}
                        <tr>
                            <td>{{ appli_news.publish_date|date:"SHORT_DATE_FORMAT" }}</td>
                            <td>{{ appli_news.news|linebreaksbr }}</td>
                        </tr>
                    {% empty %}
                        <tr><td colspan="2">{% trans "No news." %}.</td></tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div><!-- /.col-sm- -->
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "Last books registered" %}</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>{% trans "Registration date" %}</th>
                            <th>{% trans "Book" %}</th>
                            <th>{% trans "Author" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for book in last_books_list %}
                        <tr>
                            <td>{{ book.created_on|date:"SHORT_DATE_FORMAT" }}</td>
                            <td><a href="{% url 'alessandria:book_update' book.id %}">{{ book }}</a></td>
                            <td><a href="{% url 'alessandria:author_update' book.authors.first.id %}">{{ book.authors.first }}</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div><!-- /.col-sm- -->
</div>
{% endblock %}